import { Router } from "express";
import { authenticateToken } from "../middleware/auth";
import { trackEvent, getFunnelOverview, getFunnelByChannel, getFunnelByCountry, getFunnelByDevice, getDropAnalysis } from "../controllers/conversionFunnelController";
const router = Router();
router.post("/event",         authenticateToken, trackEvent);
router.get( "/overview",      authenticateToken, getFunnelOverview);
router.get( "/by-channel",    authenticateToken, getFunnelByChannel);
router.get( "/by-country",    authenticateToken, getFunnelByCountry);
router.get( "/by-device",     authenticateToken, getFunnelByDevice);
router.get( "/drop-analysis", authenticateToken, getDropAnalysis);
export default router;
