import { Router } from "express";
import { authenticateToken } from "../middleware/auth";
import { trackEvent, getFunnelOverview, getFunnelByChannel, getFunnelByCountry, getFunnelByDevice, getDropAnalysis } from "../controllers/conversionFunnelController";
const router = Router();
router.use(authenticateToken as any);
router.post("/event",         trackEvent        as any);
router.get( "/overview",      getFunnelOverview as any);
router.get( "/by-channel",    getFunnelByChannel as any);
router.get( "/by-country",    getFunnelByCountry as any);
router.get( "/by-device",     getFunnelByDevice  as any);
router.get( "/drop-analysis", getDropAnalysis    as any);
export default router;
