import { Router } from "express";
import { authenticateToken } from "../middleware/auth";
import { getCLVOverview, getSegments, getCohorts, getTopCustomers, predictCLV } from "../controllers/customerCLVController";
const router = Router();
router.use(authenticateToken as any);
router.get("/overview",            getCLVOverview   as any);
router.get("/segments",            getSegments      as any);
router.get("/cohorts",             getCohorts       as any);
router.get("/top",                 getTopCustomers  as any);
router.get("/predict/:customerId", predictCLV       as any);
export default router;
