import { Router } from "express";
import { authenticateToken } from "../middleware/auth";
import { getCLVOverview, getSegments, getCohorts, getTopCustomers, predictCLV } from "../controllers/customerCLVController";
const router = Router();
router.get("/overview",            authenticateToken, getCLVOverview);
router.get("/segments",            authenticateToken, getSegments);
router.get("/cohorts",             authenticateToken, getCohorts);
router.get("/top",                 authenticateToken, getTopCustomers);
router.get("/predict/:customerId", authenticateToken, predictCLV);
export default router;
