import { Router } from "express";
import { authenticateToken } from "../middleware/auth";
import { getLiveMetrics, getDrillDown, recordMetric, getSummary } from "../controllers/realtimeDashboardController";
const router = Router();
router.use(authenticateToken as any);
router.get( "/live",       getLiveMetrics as any);
router.get( "/drill-down", getDrillDown   as any);
router.get( "/summary",    getSummary     as any);
router.post("/record",     recordMetric   as any);
export default router;
