import { Router } from "express";
import { authenticateToken } from "../middleware/auth";
import { getOverview, getByMethod, getByCountry, getByCustomer, getByChannel, getTimeline } from "../controllers/revenueBreakdownController";
const router = Router();
router.use(authenticateToken as any);
router.get("/overview",    getOverview   as any);
router.get("/by-method",   getByMethod   as any);
router.get("/by-country",  getByCountry  as any);
router.get("/by-customer", getByCustomer as any);
router.get("/by-channel",  getByChannel  as any);
router.get("/timeline",    getTimeline   as any);
export default router;
