import { Router } from "express";
import { authenticateToken } from "../middleware/auth";
import { getOverview, getByMethod, getByCountry, getByCustomer, getByChannel, getTimeline } from "../controllers/revenueBreakdownController";
const router = Router();
router.get("/overview",    authenticateToken, getOverview);
router.get("/by-method",   authenticateToken, getByMethod);
router.get("/by-country",  authenticateToken, getByCountry);
router.get("/by-customer", authenticateToken, getByCustomer);
router.get("/by-channel",  authenticateToken, getByChannel);
router.get("/timeline",    authenticateToken, getTimeline);
export default router;
