import { Router } from "express";
import { authenticateToken } from "../middleware/auth";
import { getOverview, getByBank, getByCountry, getByMethod, getFailureReasons } from "../controllers/successRateAnalysisController";
const router = Router();
router.use(authenticateToken as any);
router.get("/overview",        getOverview       as any);
router.get("/by-bank",         getByBank         as any);
router.get("/by-country",      getByCountry      as any);
router.get("/by-method",       getByMethod       as any);
router.get("/failure-reasons", getFailureReasons as any);
export default router;
