import { Router } from "express";
import { authenticateToken } from "../middleware/auth";
import { getOverview, getByBank, getByCountry, getByMethod, getFailureReasons } from "../controllers/successRateAnalysisController";
const router = Router();
router.get("/overview",        authenticateToken, getOverview);
router.get("/by-bank",         authenticateToken, getByBank);
router.get("/by-country",      authenticateToken, getByCountry);
router.get("/by-method",       authenticateToken, getByMethod);
router.get("/failure-reasons", authenticateToken, getFailureReasons);
export default router;
