// ─────────────────────────────────────────────────────────────
// src/controllers/followUp.controller.ts
// Zyrix Backend — Smart Follow-up
// Color: #059669
// ─────────────────────────────────────────────────────────────
import { Response, NextFunction } from "express"
import { AuthenticatedRequest } from "../types"
import { prisma } from "../config/database"

// ─── Types ────────────────────────────────────────────────────

interface FollowUpRow {
  id: string
  merchant_id: string
  entity_type: string
  entity_id: string
  entity_label: string
  contact_name: string
  contact_phone: string | null
  contact_email: string | null
  amount: number | null
  currency: string
  channel: string
  status: string
  priority: string
  scheduled_at: string
  done_at: string | null
  notes: string | null
  auto_generated: boolean
  created_at: string
  updated_at: string
}

interface StatsRow {
  total: number
  pending: number
  done: number
  snoozed: number
  overdue: number
}

function mapRow(r: FollowUpRow) {
  return {
    id:           r.id,
    entityType:   r.entity_type,
    entityId:     r.entity_id,
    entityLabel:  r.entity_label,
    contactName:  r.contact_name,
    contactPhone: r.contact_phone,
    contactEmail: r.contact_email,
    amount:       r.amount !== null ? Number(r.amount) : null,
    currency:     r.currency,
    channel:      r.channel,
    status:       r.status,
    priority:     r.priority,
    scheduledAt:  r.scheduled_at,
    doneAt:       r.done_at,
    notes:        r.notes,
    autoGenerated: r.auto_generated,
    createdAt:    r.created_at,
  }
}

// ─── Controller ──────────────────────────────────────────────

export const followUpController = {

  // ── List ──────────────────────────────────────────────────
  async list(req: AuthenticatedRequest, res: Response, next: NextFunction) {
    try {
      const { status, priority, entity_type, date } = req.query as Record<string, string>
      const merchantId = req.merchant.id

      let where = `WHERE merchant_id = $1`
      const params: unknown[] = [merchantId]
      let idx = 2

      if (status)      { where += ` AND status = $${idx++}`;      params.push(status.toUpperCase()) }
      if (priority)    { where += ` AND priority = $${idx++}`;    params.push(priority.toUpperCase()) }
      if (entity_type) { where += ` AND entity_type = $${idx++}`; params.push(entity_type.toUpperCase()) }
      if (date)        { where += ` AND DATE(scheduled_at) = $${idx++}`; params.push(date) }

      const rows = await prisma.$queryRawUnsafe<FollowUpRow[]>(
        `SELECT * FROM follow_ups ${where} ORDER BY scheduled_at ASC`,
        ...params
      )

      res.json({ success: true, data: rows.map(mapRow) })
    } catch (err) { next(err) }
  },

  // ── Stats ─────────────────────────────────────────────────
  async getStats(req: AuthenticatedRequest, res: Response, next: NextFunction) {
    try {
      const merchantId = req.merchant.id
      const now = new Date().toISOString()

      const rows = await prisma.$queryRawUnsafe<StatsRow[]>(
        `SELECT
           COUNT(*)::int                                                          AS total,
           COUNT(*) FILTER (WHERE status = 'PENDING')::int                       AS pending,
           COUNT(*) FILTER (WHERE status = 'DONE')::int                          AS done,
           COUNT(*) FILTER (WHERE status = 'SNOOZED')::int                       AS snoozed,
           COUNT(*) FILTER (WHERE status = 'PENDING' AND scheduled_at < $2)::int AS overdue
         FROM follow_ups WHERE merchant_id = $1`,
        merchantId, now
      )

      const todayStart = new Date(); todayStart.setHours(0,0,0,0)
      const todayEnd   = new Date(); todayEnd.setHours(23,59,59,999)

      const todayRows = await prisma.$queryRawUnsafe<{ count: number }[]>(
        `SELECT COUNT(*)::int AS count FROM follow_ups
         WHERE merchant_id = $1 AND status = 'PENDING'
           AND scheduled_at BETWEEN $2 AND $3`,
        merchantId, todayStart.toISOString(), todayEnd.toISOString()
      )

      res.json({
        success: true,
        data: {
          total:   Number(rows[0]?.total   || 0),
          pending: Number(rows[0]?.pending || 0),
          done:    Number(rows[0]?.done    || 0),
          snoozed: Number(rows[0]?.snoozed || 0),
          overdue: Number(rows[0]?.overdue || 0),
          today:   Number(todayRows[0]?.count || 0),
        },
      })
    } catch (err) { next(err) }
  },

  // ── Create ────────────────────────────────────────────────
  async create(req: AuthenticatedRequest, res: Response, next: NextFunction) {
    try {
      const {
        entityType, entityId, entityLabel,
        contactName, contactPhone, contactEmail,
        amount, currency = "SAR", channel,
        priority = "MEDIUM", scheduledAt, notes,
      } = req.body as {
        entityType: string; entityId: string; entityLabel: string
        contactName: string; contactPhone?: string; contactEmail?: string
        amount?: number; currency?: string; channel: string
        priority?: string; scheduledAt: string; notes?: string
      }

      if (!entityType || !entityId || !entityLabel || !contactName || !channel || !scheduledAt) {
        res.status(400).json({ success: false, error: { code: "VALIDATION_ERROR", message: "الحقول المطلوبة: entityType, entityId, entityLabel, contactName, channel, scheduledAt" } })
        return
      }

      const rows = await prisma.$queryRawUnsafe<FollowUpRow[]>(
        `INSERT INTO follow_ups
           (merchant_id, entity_type, entity_id, entity_label, contact_name, contact_phone,
            contact_email, amount, currency, channel, priority, scheduled_at, notes)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
         RETURNING *`,
        req.merchant.id,
        entityType.toUpperCase(), entityId, entityLabel,
        contactName, contactPhone ?? null, contactEmail ?? null,
        amount ?? null, currency.toUpperCase(),
        channel.toUpperCase(), priority.toUpperCase(),
        scheduledAt, notes ?? null
      )

      res.json({ success: true, data: mapRow(rows[0]) })
    } catch (err) { next(err) }
  },

  // ── Update Status ─────────────────────────────────────────
  async updateStatus(req: AuthenticatedRequest, res: Response, next: NextFunction) {
    try {
      const { id } = req.params
      const { status, notes } = req.body as { status: string; notes?: string }

      if (!["PENDING","DONE","SNOOZED","CANCELLED"].includes(status?.toUpperCase())) {
        res.status(400).json({ success: false, error: { code: "VALIDATION_ERROR", message: "status غير صحيح" } })
        return
      }

      const doneAt = status.toUpperCase() === "DONE" ? new Date().toISOString() : null

      const rows = await prisma.$queryRawUnsafe<FollowUpRow[]>(
        `UPDATE follow_ups
         SET status = $1, done_at = $2, notes = COALESCE($3, notes), updated_at = NOW()
         WHERE id = $4 AND merchant_id = $5
         RETURNING *`,
        status.toUpperCase(), doneAt, notes ?? null, id, req.merchant.id
      )

      if (rows.length === 0) {
        res.status(404).json({ success: false, error: { code: "NOT_FOUND", message: "المتابعة غير موجودة" } })
        return
      }

      res.json({ success: true, data: mapRow(rows[0]) })
    } catch (err) { next(err) }
  },

  // ── Snooze ────────────────────────────────────────────────
  async snooze(req: AuthenticatedRequest, res: Response, next: NextFunction) {
    try {
      const { id } = req.params
      const { scheduledAt } = req.body as { scheduledAt: string }

      if (!scheduledAt) {
        res.status(400).json({ success: false, error: { code: "VALIDATION_ERROR", message: "scheduledAt مطلوب" } })
        return
      }

      const rows = await prisma.$queryRawUnsafe<FollowUpRow[]>(
        `UPDATE follow_ups
         SET status = 'SNOOZED', scheduled_at = $1, updated_at = NOW()
         WHERE id = $2 AND merchant_id = $3
         RETURNING *`,
        scheduledAt, id, req.merchant.id
      )

      res.json({ success: true, data: rows[0] ? mapRow(rows[0]) : null })
    } catch (err) { next(err) }
  },

  // ── Delete ────────────────────────────────────────────────
  async delete(req: AuthenticatedRequest, res: Response, next: NextFunction) {
    try {
      await prisma.$executeRawUnsafe(
        `DELETE FROM follow_ups WHERE id = $1 AND merchant_id = $2`,
        req.params.id, req.merchant.id
      )
      res.json({ success: true, data: { deleted: true } })
    } catch (err) { next(err) }
  },

  // ── Auto-generate from overdue invoices ───────────────────
  async autoGenerate(req: AuthenticatedRequest, res: Response, next: NextFunction) {
    try {
      const merchantId = req.merchant.id

      // جلب الفواتير المتأخرة
      const overdueInvoices = await prisma.invoice.findMany({
        where: { merchantId, status: { in: ["OVERDUE", "SENT"] }, dueDate: { lt: new Date() } },
        take: 20,
      })

      let created = 0

      for (const inv of overdueInvoices) {
        // تحقق إن مفيش follow-up موجود لنفس الفاتورة
        const existing = await prisma.$queryRawUnsafe<{ count: number }[]>(
          `SELECT COUNT(*)::int AS count FROM follow_ups
           WHERE merchant_id = $1 AND entity_id = $2 AND status = 'PENDING'`,
          merchantId, inv.id
        )

        if (Number(existing[0]?.count) > 0) continue

        const daysOverdue = Math.floor((Date.now() - inv.dueDate.getTime()) / 86400000)
        const priority    = daysOverdue > 14 ? "HIGH" : daysOverdue > 7 ? "MEDIUM" : "LOW"
        const scheduledAt = new Date(Date.now() + 3600000).toISOString() // بعد ساعة

        await prisma.$executeRawUnsafe(
          `INSERT INTO follow_ups
             (merchant_id, entity_type, entity_id, entity_label, contact_name,
              amount, currency, channel, priority, scheduled_at, auto_generated, notes)
           VALUES ($1,'INVOICE',$2,$3,$4,$5,$6,'WHATSAPP',$7,$8,TRUE,$9)`,
          merchantId, inv.id,
          `فاتورة ${inv.invoiceId}`,
          inv.customerName,
          Number(inv.total),
          inv.currency,
          priority,
          scheduledAt,
          `متأخرة ${daysOverdue} يوم`
        )
        created++
      }

      res.json({
        success: true,
        data: { created, message: `تم إنشاء ${created} متابعة تلقائية` },
      })
    } catch (err) { next(err) }
  },

  // ── Today's Follow-ups ────────────────────────────────────
  async getToday(req: AuthenticatedRequest, res: Response, next: NextFunction) {
    try {
      const todayStart = new Date(); todayStart.setHours(0,0,0,0)
      const todayEnd   = new Date(); todayEnd.setHours(23,59,59,999)

      const rows = await prisma.$queryRawUnsafe<FollowUpRow[]>(
        `SELECT * FROM follow_ups
         WHERE merchant_id = $1
           AND scheduled_at BETWEEN $2 AND $3
           AND status IN ('PENDING','SNOOZED')
         ORDER BY priority DESC, scheduled_at ASC`,
        req.merchant.id,
        todayStart.toISOString(),
        todayEnd.toISOString()
      )

      res.json({ success: true, data: rows.map(mapRow) })
    } catch (err) { next(err) }
  },
}
